### ISSUE TITLE
Can botkube work in an airgapped environment? 

### ISSUE THREAD

**Issue by metalshanked** [kubeshop/botkube#1038]
Hi,
I see some external internet URL dependencies.
The usecase is a simple webhook notifier for events (just like Kubewatch which works on airgapped installs)

thanks!

**Comment by pkosiec** [comment]
Hi @metalshanked,
In theory, it _could be_ possible, as Botkube plugin manager downloads plugin repo data (including plugins and theirs dependencies) only if they don't exist on a disk. Source: https://github.com/kubeshop/botkube/blob/a69f7cfccc768877f7a6027817b720442987dffc/internal/plugin/manager.go
We download all the files on `emptyDir` volume mounted to the Pod:
https://github.com/kubeshop/botkube/blob/a69f7cfccc768877f7a6027817b720442987dffc/helm/botkube/templates/deployment.yaml#L166

So while it is not there out of the box, with some small Helm chart adjustments, or using a custom image with all plugins + plugin index embedded, that could be possible. Such scenario is not documented, simply because Botkube is the best when used with chat platform. Webhook is one-way only integration, where you miss the power of e.g. debugging your Kubernetes cluster collaboratively.

However, we might think about building an image with all official plugins already downloaded, if there will be a need from our community 🤔 This would help with e.g. slow internet connection problems.

**Comment by olfway** [comment]
> we might think about building an image with all official plugins already downloaded
We also interested in this, for us it's better to have an image with default plugins included
