### ISSUE TITLE
False alarm on deployment update

### ISSUE THREAD

**Issue by hyeongkyu-park** [kubeshop/botkube#1139]
## Description

In Botkube v1.1.1, I set the strategy for deployment in sources. 'k8s-all-events'.botkube/kuvernets.config.resource as below.

 ```
- type: apps/v1/deployments
   event: # Overrides 'source'.kubernetes.event
     types:
       - create
       - update
       - delete
       - error
   updateSetting:
     includeDiff: true
     fields:
       - spec.template.spec.containers[*].image
```

My intention was to receive an update alarm only when the image declared in updateSetting.fields changes, but when there is no change in reality, suddenly an update alarm for all deployments in the cluster is sent to the slack.

In fact, if I look at the cluster, no changes are detected in any deployment where the alarm came on. (Change in replica count or restart, etc.)

This happens periodically every 30 minutes.

## Expected behavior

My intention was to receive an update alarm only when the image declared in updateSetting.fields changes.

## Actual behavior

When there is no change in reality, suddenly an update alarm for all deployments in the cluster is sent to the slack.

**Comment by mszostok** [comment]
Hi @hyeongkyu-park 

Unfortunately, that’s because of the bug that we had since 1.0.0, however we already fixed that and it will be released soon, most probably next Monday as v1.2.0. 

For the reference, see:
- https://github.com/kubeshop/botkube/issues/1081
- https://github.com/kubeshop/botkube/pull/1122

Apologies for any inconvenience!
