### ISSUE TITLE
Able to display specific container log in a pod

### ISSUE THREAD

**Issue by mts-dyt** [kubeshop/botkube#1187]
## Overview
Select the container when executing `kubectl logs <pod>`

## Acceptance Criteria
- kubebot command allows to select a specific container to display logs

## Reason
When we have multiple containers in a pod, it is always displayed the logs of the first container

**Comment by pkosiec** [comment]
Hey @mts-dyt,
I'm closing this issue as resolved. Feel free to reopen the issue if your problem is not resolved  🙂 Ensure you use the latest Botkube version. Cheers!

**Comment by mts-dyt** [comment]
hi @pkosiec 
Yes the command is OK but the idea was to able to select the container from slack

**Comment by pkosiec** [comment]
Hey @mts-dyt,
 Ah, you mean the interactive dropdown? If so, we have such issue already: https://github.com/kubeshop/botkube/issues/949. Please follow it for updates. For now this is not planned to any of the upcoming milestones, but that might change soon. Please add a reaction under #949 so that we can see the popularity of the feature request. Thanks!
