### ISSUE TITLE
Dog-food ArgoCD plugin

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#1239]
## Description

- use Botkube Argo CD plugin for our deployments to see more insights about the status on our configured channels
   - scenario:
      - we update the App version
      - we get notification that app is being deployed
      - if case of error we are notified about it also. For example, 
        - `Error: secret "botkube-api-key" not found`
- To use latest plugins, we need to use dev env with BotkubeDev app (scoped to Botkube Playground only). So we'll need to have a dev Botkube installation installed on dev cluster, and watch a channel on Botkube Playground.
   
   Gather feedback from the Kubefirst/Testkube team.

**Comment by josefkarasek** [comment]
Learnings after enabling argocd plugin in test env:

1. Onboarding multiple apps requires too much typing, having a label selector and/or regular expression would improve this process
2. Sometimes some fields in a notification are empty, eg. `Initiated by : <no value>`, because in this case the operation wasn't initiated by a human user. We should put a note in our docs that it's expected.
3. Argo itself does not revert the annotations that we put on Application resources - we don't have to take any actions here (initially we envisioned a dry-run mode for the plugin and more predictable names for the annotations)
4. A minor typo
5. No bugs were discovered
