### ISSUE TITLE
Multiple Slack Channels

### ISSUE THREAD

**Issue by akath19** [kubeshop/botkube#250]
**Is your feature request related to a problem? Please describe.**
I'm running botkube as a PoC for my company, we have one cluster per team for non-prod environments & one cluster per team for prod environments, each team wants to be able to manage only their clusters.

This poses a problem because `@BotKube` doesn't have awareness of the channel and allows running `kubectl` commands for all clusters it knows about and running `ping` will give the user the list of all clusters configured.

**Describe the solution you'd like**
I'd love for botkube to be able to work on multiple slack channels while keeping context of each of them, specifically, I would like to have separate botkubes that have access to only one cluster in a single Slack workspace

**Describe alternatives you've considered**
I tried to find a way to add multiple botkube instances to slack but adding to a Slack workspace will always render the same token.

I have added botkube to a few channels but all channels have  access to all clusters

**Additional context**
Having this would allow me to manage all my clusters and allow my teams to manage their clusters separately without them needing either kubectl or having access to clusters not their own

I found [this](https://github.com/infracloudio/botkube/issues/37) ticket that seemed to describe something similar, however, it's not the same request

**Comment by McOffsky** [comment]
The token for botkube slack app will always be the same, its not related to the channel value. Both of those are stored in botkube-communication-secret. For now the workaround would be to create another deployment for botkube, that for communication uses diffrent secret, with the same token, and diffrent channel.

**Comment by mleklund** [comment]
I'd like to send errors to a specific channel, and the chaff to another, so I am in the same boat.

**Comment by sramek5** [comment]
Well, I would like to have a same feature.
We use BotKube in our Slack to notify about Deployment tool status directly to responsible person "@name.surname" instead of channel.
It would be great, if BotKube could mention status to more persons and also public channel.
For example like this:
```
slack:
    enabled: true
    channel: ["@joe.barbado", "@frankie.sucks", "devel-status"]
```

**Comment by dmthomson** [comment]
Use case for sending event one channel vs kubectl access to another. 

> Well, I would like to have a similar feature.
> 
> We use BotKube in our Slack to notify about Deployment tool status directly to responsible person "@name.surname" instead of channel.
> 
> It would be great, if BotKube could mention status to more persons and also public channel.
> 
> For example like this:
> 
> ```
> slack:
>     enabled: true
>     channels: ["@joe.barbado", "@frankie.sucks", "devel-status"]
> ```

Since you already have it going to a dedicate person did you try using @slack_group?

**Comment by dmthomson** [comment]
I would love to be able to route functionality to different channels instead of all in one without needing to run multiple deployments. 

Events could go to a certain channel, k8s commands another. etc

**Comment by dsaydon90** [comment]
related https://github.com/infracloudio/botkube/issues/508 ?

**Comment by mszostok** [comment]
This issue is not related strictly to the multichannel support as defined in https://github.com/infracloudio/botkube/issues/596. 

Here is the main difference:
>I'd love for botkube to be able to work on multiple slack channels while keeping context of each of them, specifically, I would like to have separate botkubes that have access to only one cluster in a single Slack workspace

Currently, you are able to do that:
- to limit the `kubectl` executor access, add `--set config.settings.kubectl.restrictAccess=true` during Helm chart installation (or put this in `values.yaml`).
- to send the notification, just specify a proper `communication.slack.channel` per deployment.


## Findings

However, this solution has a few problems:

1. It works only if you will deploy one BotKube per cluster/channel. But it's what you asked for.
2. The `@BotKube ping` command returns information about all registered cluster, even if a given channel is not authorized with a given channel. **IMO, it's a bug.** 
3. If you send the `@BotKube get po --cluster-name prod` from a channel that is not authorized, you will not get any response. IMO, it makes pure UX experience. It should print sth like:
    ```
    Cluster "prod" is not registered or channel is not authorized to access it.
    ```
    Related issue: https://github.com/infracloudio/botkube/issues/402

    
4. If you use the `botkube.io/channel: <channel_name>`, notifications are sent to a given channel even if not authorized. **IMO, it's a bug.**

    However, fixing this is problematic as we will need to do that base on `config.settings.kubectl.restrictAccess` and if it is set to true, allow only `communications.<name>.channel`. It will be better to postpone that until BotKube will support multiple channels per single configuration. For example:
  
    ```yaml
    slack:
      enabled: true
      channels: ["@foo", "@bar", "devel-status"]
    ```

### Action Items

1. Fix bugs:
  - The `@BotKube ping` should return only clusters that are authorized clusters with a given channel.
  - If the `botkube.io/channel: <channel_name>` annotation is used, send notification only if a given channel is authorized. Do that after https://github.com/infracloudio/botkube/issues/596.
    
2. Improve UX:
  - If cluster is not authorized, instead of ignoring, send info:
    ```
    Cluster "prod" is not registered or channel is not authorized to access it.
    ```

**Comment by pkosiec** [comment]
Hi all,

Closing as the requested features along with the UX improvements were implemented in https://github.com/kubeshop/botkube/issues/596. 
When it comes to resource annotations, I put the requirements in an aggregated task for reworking the feature: https://github.com/kubeshop/botkube/issues/690

Feel free to reopen the issue or create another ones with a description of what's missing in the new configuration features, after trying out BotKube 0.13. It's just around the corner, so stay tuned!
